-- Alma Universe - EBD Devices Seed Data
-- Run this in Supabase SQL Editor after creating the ebd_devices table
-- This inserts all 19 Energy-Based Device products

INSERT INTO ebd_devices (id, name, description, treats, fitzpatrick, downtime, tags, product_family, image_url, is_active)
VALUES
  (
    'alma-harmony-clearlift-pro-1064',
    'Alma Harmony - ClearLift Pro 1064',
    'ClearLift Pro 1064 utilizes non-thermal laser energy to target and break down pigmentation, while progressively enhancing skin quality through a series of treatments.',
    ARRAY['Melasma', 'Texture (pores, scars)', 'Dark spots', 'Pigmentation', 'Wrinkles', 'Skin quality (laxity)'],
    'I-VI',
    'None',
    ARRAY['Alma Harmony', '1064', 'ClearLift', 'ClearLift Pro', 'Harmony', 'Laser treatment', 'Skin remodeling'],
    'Alma Harmony',
    NULL,
    true
  ),
  (
    'alma-harmony-clearlift-pro-532',
    'Alma Harmony - ClearLift Pro 532',
    'ClearLift Pro 532 employs non-thermal laser energy to effectively break down pigmentation over a series of treatments.',
    ARRAY['Dark spots (cafe-au-lait, lentigo)'],
    'I-III',
    'Minimal',
    ARRAY['Alma Harmony', 'ClearLift', '532', 'Harmony', 'Laser treatment', 'Skin remodeling'],
    'Alma Harmony',
    NULL,
    true
  ),
  (
    'alma-harmony-clearskin-pro',
    'Alma Harmony - ClearSkin Pro',
    'ClearSkin Pro utilizes laser energy to deliver controlled thermal injury to targeted areas of the skin, stimulating improvements in skin quality and texture.',
    ARRAY['Texture (pores, scars)', 'Wrinkles', 'Skin quality (laxity)'],
    'I-V',
    'Minimal',
    ARRAY['Alma Harmony', 'Harmony', 'ClearSkin', '1540', 'Laser treatment', 'Skin remodeling'],
    'Alma Harmony',
    NULL,
    true
  ),
  (
    'alma-harmony-iris-dye-vl',
    'Alma Harmony - Iris Dye-VL',
    'Iris Dye-VL uses intense pulsed light (IPL) technology to effectively treat redness and visible veins.',
    ARRAY['Redness (rosacea, acne scars)', 'Vascularity', 'Pigmentation'],
    'I-IV',
    'Minimal',
    ARRAY['Alma Harmony', 'Dye-VL', 'Harmony', 'IPL treatment'],
    'Alma Harmony',
    NULL,
    true
  ),
  (
    'alma-harmony-superb',
    'Alma Harmony - SupErb',
    'SupErb uses laser energy to precisely ablate a fraction of the skin''s surface, targeting fine lines and wrinkles. The laser removes damaged outer layers while stimulating and toning the deeper layers, resulting in smoother, firmer skin.',
    ARRAY['Texture (pores, scars)', 'Wrinkles', 'Dark spots'],
    'I-IV',
    'Some',
    ARRAY['Alma Harmony', 'SupErb', 'Harmony', '2940', 'Laser treatment', 'Skin resurfacing'],
    'Alma Harmony',
    NULL,
    true
  ),
  (
    'alma-harmony-vascupen',
    'Alma Harmony - VascuPen',
    'VascuPen uses precise energy to treat and eliminate visible veins on the face.',
    ARRAY['Vascularity'],
    'I-IV',
    'Minimal',
    ARRAY['Vascupen', 'Alma Harmony', 'Harmony', 'Laser treatment'],
    'Alma Harmony',
    NULL,
    true
  ),
  (
    'alma-hybrid-hyper-co2-1570',
    'Alma Hybrid - HyPer (CO2:1570)',
    'HyPer (CO2:1570) combines laser energies to smooth fine lines and wrinkles. The CO2 laser ablates damaged outer skin layers, while the 1570 nm wavelength tones the deeper layers, resulting in smoother, firmer skin.',
    ARRAY['Texture (pores, scars)', 'Wrinkles', 'Pigmentation'],
    'I-V',
    'Minimal',
    ARRAY['CO2', 'HyPer', 'Alma Hybrid', '1570', 'Hybrid', 'Laser treatment', 'Skin remodeling', 'Skin resurfacing'],
    'Alma Hybrid',
    NULL,
    true
  ),
  (
    'alma-hybrid-pixelpeel',
    'Alma Hybrid - PixelPeel',
    'PixelPeel is a gentle, pixelated laser peel that exfoliates the skin''s surface, revealing a smoother, more polished finish.',
    ARRAY['Pigmentation', 'Redness (rosacea, acne scars)', 'Texture (pores, scars)', 'Fine lines', 'Skin quality (laxity)'],
    'I-VI',
    'Minimal',
    ARRAY['Proscan CO2', 'CO2', 'Alma Hybrid', 'Hybrid', 'Laser treatment', 'Skin resurfacing'],
    'Alma Hybrid',
    NULL,
    true
  ),
  (
    'alma-hybrid-proscan-1570',
    'Alma Hybrid - Proscan 1570',
    'Proscan 1570 uses laser energy to deliver controlled thermal injury to targeted fractions of the skin, promoting improved skin quality and texture.',
    ARRAY['Texture (pores, scars)', 'Wrinkles', 'Skin quality (laxity)'],
    'I-V',
    'Minimal',
    ARRAY['ProScan 1570', 'Alma Hybrid', '1570', 'Hybrid', 'Laser treatment', 'Skin remodeling'],
    'Alma Hybrid',
    NULL,
    true
  ),
  (
    'alma-hybrid-proscan-co2',
    'Alma Hybrid - Proscan CO2',
    'Proscan CO2 uses laser energy to precisely ablate a fraction of the skin, effectively smoothing fine lines and wrinkles.',
    ARRAY['Pigmentation', 'Dark spots', 'Texture (pores, scars)', 'Wrinkles'],
    'I-IV',
    'Some',
    ARRAY['CO2', 'ProScan CO2', 'Alma Hybrid', 'Hybrid', 'Laser treatment', 'Skin resurfacing'],
    'Alma Hybrid',
    NULL,
    true
  ),
  (
    'alma-pixel-pixelpeel',
    'Alma Pixel - PixelPeel',
    'PixelPeel is a gentle, pixelated laser peel that exfoliates the skin''s surface, revealing a smoother, more polished finish.',
    ARRAY['Pigmentation', 'Redness (rosacea, acne scars)', 'Texture (pores, scars)', 'Fine lines', 'Skin quality (laxity)'],
    'I-VI',
    'Minimal',
    ARRAY['LightScan', 'CO2', 'Alma Pixel', 'Laser treatment', 'Skin resurfacing'],
    'Alma Pixel',
    NULL,
    true
  ),
  (
    'alma-veil-1064',
    'Alma Veil - 1064 (blue/purple vascular)',
    'Alma Veil 1064 uses laser energy to deliver controlled thermal injury, effectively treating unwanted vascularity on the face and body.',
    ARRAY['Vascularity (periorbital veins, leg veins)'],
    'I-VI',
    'Minimal',
    ARRAY['1064', 'Veil', 'Alma Veil', 'Laser treatment'],
    'Alma Veil',
    NULL,
    true
  ),
  (
    'alma-veil-532',
    'Alma Veil - 532',
    'Alma Veil 532 uses laser energy to deliver controlled thermal injury, effectively treating unwanted vascularity and pigmentation.',
    ARRAY['Redness (rosacea, acne scars)', 'Vascularity (telangiectasias, angiomas)', 'Dark spots'],
    'I-IV',
    'Minimal',
    ARRAY['Veil', 'Alma Veil', '532', 'Laser treatment'],
    'Alma Veil',
    NULL,
    true
  ),
  (
    'alma-veil-micropulse',
    'Alma Veil - MicroPulse',
    'MicroPulse uses laser energy to deliver a controlled thermal effect that stimulates dermal remodeling.',
    ARRAY['Melasma', 'Redness (rosacea, acne scars)', 'Texture (pores, scars)', 'Wrinkles', 'Skin quality (laxity)', 'Pigmentation'],
    'I-VI',
    'None',
    ARRAY['1064', 'Veil', 'Alma Veil', 'MicroPulse', 'Laser treatment', 'Skin remodeling'],
    'Alma Veil',
    NULL,
    true
  ),
  (
    'harmony-xl-pro-clearlift-1064',
    'Harmony XL Pro - ClearLift 1064',
    'ClearLift 1064 utilizes non-thermal laser energy to gradually break down pigmentation and improve skin quality over a series of treatments.',
    ARRAY['Melasma', 'Texture (pores, scars)', 'Dark spots', 'Pigmentation', 'Wrinkles', 'Skin quality (laxity)'],
    'I-VI',
    'None',
    ARRAY['1064', 'ClearLift', 'Harmony XL Pro', 'Harmony', 'Laser treatment', 'Skin remodeling'],
    'Harmony XL Pro',
    NULL,
    true
  ),
  (
    'harmony-xl-pro-dye-vl',
    'Harmony XL Pro - Dye VL',
    'Dye VL uses intense pulsed light (IPL) to effectively treat redness and pigmentary concerns in UV-exposed areas of the face and body.',
    ARRAY['Redness (rosacea, acne scars)', 'Sun damage'],
    'I-IV',
    'Minimal',
    ARRAY['Dye VL', 'Harmony XL Pro', 'Harmony', 'IPL treatment'],
    'Harmony XL Pro',
    NULL,
    true
  ),
  (
    'harmony-xl-pro-ipixeler',
    'Harmony XL Pro - iPixelER',
    'iPixelER uses laser energy to precisely ablate a fraction of the skin''s surface, targeting fine lines and wrinkles. The damaged outer layers are removed, while deeper layers are stimulated and toned for a smoother, firmer appearance.',
    ARRAY['Texture (pores, scars)', 'Wrinkles', 'Dark spots'],
    'I-IV',
    'Some',
    ARRAY['Erbium', 'iPixel', 'Harmony XL Pro', 'Harmony', 'Laser treatment', 'Skin resurfacing'],
    'Harmony XL Pro',
    NULL,
    true
  ),
  (
    'opus-colibri',
    'Opus - Colibri (periorbital)',
    'Opus Colibri utilizes micro-plasma energy to deliver controlled ablation and thermal coagulation, thereby enhancing skin quality in the sensitive eye area.',
    ARRAY['Wrinkles', 'Skin quality (laxity) around eyes'],
    'I-III',
    'Some',
    ARRAY['Colibri', 'Opus', 'RF treatment', 'Skin resurfacing', 'Skin remodeling'],
    'Opus',
    NULL,
    true
  ),
  (
    'opus-plasma',
    'Opus - Plasma',
    'Opus Plasma uses fractional plasma energy to ablate damaged outer skin layers while simultaneously heating deeper tissues, promoting a smoother, firmer appearance.',
    ARRAY['Pigmentation', 'Melasma', 'Redness (rosacea, acne scars)', 'Texture (pores, scars)', 'Wrinkles', 'Skin quality (laxity)'],
    'I-VI',
    'Minimal',
    ARRAY['Opus', 'Plasma', 'Fractional Plasma', 'RF treatment', 'Skin resurfacing', 'Skin remodeling'],
    'Opus',
    NULL,
    true
  );
